using Lelleplanner.Core;
using System;
using System.Linq;

Console.WriteLine("Loading old GameState...");
var gameState = Persistence.LoadOrCreate();
var gameEngine = new GameEngine();
Console.WriteLine("Game Date: " + gameState.GameDate.ToString());
Console.WriteLine("Coins: " + gameState.DailyCoins);
Console.WriteLine("Quests Completed: " + gameState.Quests.Count(q => q.Completed) + "/" + "7");
Console.WriteLine("Completing quests...");
gameEngine.CompleteQuest(gameState, "food-for-thought");
gameEngine.CompleteQuest(gameState, "shiny-pearly-whites");
gameEngine.CompleteQuest(gameState, "buff-papaya");
gameEngine.CompleteQuest(gameState, "walk-for-life");
gameEngine.CompleteQuest(gameState, "pretty-boy-papaya");
gameEngine.CompleteQuest(gameState, "smartypants-huh");
Console.WriteLine("Quests completed!");
Console.WriteLine("Quests Completed: " + gameState.Quests.Count(q => q.Completed) + "/" + "7");
gameEngine.CompleteDailyQuest(gameState);
Console.WriteLine("Daily quest completed! 1x Daily Coin awarded.");
Console.WriteLine("Current GameState:");
Console.WriteLine("Game Date: " + gameState.GameDate.ToString());
Console.WriteLine("Coins: " + gameState.DailyCoins);
Console.WriteLine("Quests Completed: " + gameState.Quests.Count(q => q.Completed) + "/" + "7");
Console.WriteLine("Testing if Daily Quest can be completed multiple times...");
gameEngine.CompleteDailyQuest(gameState);
Console.WriteLine("Current GameState:");
Console.WriteLine("Game Date: " + gameState.GameDate.ToString());
Console.WriteLine("Coins: " + gameState.DailyCoins);
Console.WriteLine("Quests Completed: " + gameState.Quests.Count(q => q.Completed) + "/" + "7");
Console.WriteLine("Saving Game...");
Persistence.Save(gameState);